

MedBridge:
  Name: medbridge

      #################################### Default Image Tag #####################################################
      #######
      #######   Default image tag to use across all containers in the deployment. Can be overridden
      #######   for specific containers. See `Images` map below
      #######
      ############################################################################################################

  ImageTag: "48d0fc1"
  Strategy: RollingUpdate
  Replicas: 1
  LivenessProbe: true

      #################################### Logging ###############################################################
      #######
      #######   Set to true to enable the FileBeat log container, which routes logs to the ELK stack
      #######
      ############################################################################################################

  Logging: true
  Services:
    MedbridgeEdDb:

      #################################### Service Types #########################################################
      #######
      #######   Types:
      #######    * ExternalName — Point to RDS instance
      #######    * ClusterIP — Internal cluster service
      #######    * NodePort — Bind to port, accessible from outside cluster
      #######
      ############################################################################################################

      Type:

      #################################### ExernalName Service ###################################################
      #######
      #######   Set an ExternalName for services that live outside of the cluster
      #######   An RDS hostname might go here e.g. medbridge.abc123.us-west-1.rds.amazonaws.com
      #######   Leave blank if not using external name
      #######
      ############################################################################################################

      ExternalName:

    MedbridgeEdDbReadSlave:

      #################################### ExernalName Service ###################################################
      #######
      #######   Read slave ExternalName service. Used primarily in production.
      #######   An RDS hostname goes here e.g. medbridge-read-slave.abc123.us-west-1.rds.amazonaws.com
      #######   Leave blank if not using external name
      #######
      ############################################################################################################

      ExternalName:

  #################################### Secrets #########################################################
  #######
  #######   Secret values that will be used in Secrets, encrypted
  #######   resources that are available to any pod in the cluster
  #######
  ######################################################################################################

  Secrets:
    MedbridgeEdDb:
      Name: medbridge-db
      DbName: medbridge_education
      User: root
      Password: test123123
    AWS:
      Name: aws
      AccessKeyId: ABC123
      SecretAccessKeyId: ABC123
      Region: us-east-1
    NewRelic:
      Name: newrelic-license-key
      LicenseKey: abc123

  NewRelic:

    #################################### NewRelic AppName ################################################
    #######
    #######   The name that the MedBridge deployment will appear as in the NewRelic console
    #######
    ######################################################################################################

    AppName: medbridge.io
    LogLevel: verbosedebug
    LogFile: /var/log/newrelic/php_agent.log

  Persistence:
    Source:

    #################################### Source Code ####################################################
    #######
    #######   For a development environment, set HostPath below to the path to the MedBridge codebase
    #######
    ######################################################################################################

      HostPath: #/path/to/Programming/Php/Medbridge
    MySQL:

    #################################### Local Database ##################################################
    #######
    #######   For development, set HostPath below to the path to the MedBridge MySQL data directory
    #######
    ######################################################################################################

      HostPath: #/path/to/data/mysql
      AwsEbsVolumeId: #vol-abc123
      Name: medbridge-pv
      AccessMode: ReadWriteOnce
      Size: 100Gi

      #################################### Images/Tags #####################################################
      #######
      #######   The image names and tags to use in the deploy
      #######
      ######################################################################################################

  Images:
    Source:
      Image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/medbridge-php-source
      ImageTag: "48d0fc1"
    ImageAssets:
      Image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/medbridge-images
      ImageTag: "c06b929"
    Migrations:
      Image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/medbridge-migrations
      ImageTag: "48d0fc1"
    Nginx:
      Image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/medbridge-nginx
      ImageTag: "48d0fc1"
    PHPCLI:
      Image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/medbridge-migrations
      ImageTag: "48d0fc1"
    PHP:
      Image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/medbridge-phpfpm
      ImageTag: "48d0fc1"
    MySQL:
      Image: mysql
      ImageTag: 5.7


      #################################### Environment Variables ###########################################
      #######
      #######   Values that will be injected into containers as environment variables
      #######
      ######################################################################################################

  Env:
    APP_ENV: development
    MEDFLIX_HOST: medflix-svc
    ACE_HOST: ace-svc
    REPORTING_HOST: reporting-svc
    HIERARCHY_HOST: hierarchy-svc
    PATIENTSERVICE_HOST: patientservice
    MEDBRIDGE_ED_DB_HOST: medbridge-db
    MEDBRIDGE_ED_READSLAVE_HOST: medbridge-db
    XDEBUG_PORT: "10000"

  Resources:
    Nginx:
      Requests:
        CPU: 100m
        Memory: 128Mi
      Limits:
        CPU: 200m
        Memory: 128Mi
    PHPCLI:
      Requests:
        CPU: 200m
        Memory: 200m
      Limits:
        CPU: 1Gi
        Memory: 500m
    PHP:
      Requests:
        CPU: 200m
        Memory: 256Mi
      Limits:
        CPU: 1
        Memory: 2Gi
    MySQL:
      Requests:
        CPU: 500m
        Memory: 500Mi
      Limits:
        CPU: 1.5Gi
        Memory: 1000Mi

  Configs:

    ConfigMaps:
      Nginx:
        Name: medbridge-nginx-conf
        SitesEnabled:

          #################################### Sites Enabled ###################################################
          #######
          #######   An array of values from nginx.etc.nginx.sites-available.configmap.yaml that
          #######   will be pulled into /etc/nginx/sites-enabled in the nginx container
          #######
          ######################################################################################################

          - localmed.com.conf

      MySQL:
        Name: mysql-ini