# Database secret
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.packageId  }}-patientservice-token"
type: Opaque
data:
  token: {{ .Values.PatientService.SecurityToken | b64enc | quote }}
  