AWSTemplateFormatVersion: 2010-09-09
Description: >-
  App: Hydra DB
  Create EBS Volume from a snapshot for the Hydra MySQL database. 
Metadata:
  Name: ebs-hydra-mydql
Resources:
  EBSVolume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: us-west-2a
      Encrypted: false
      Size: 100
      Tags:
        - Key: datasource
          Value: hydra
      VolumeType: standard
      SnapshotId: snap-12345
Outputs:
  AwsEbsVolumeId:
    Description: AwsEbsVolumeId
    Value: !Ref EBSVolume