apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: "{{ .Values.packageId }}-{{ .Values.Hierarchy.Name }}-svc"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component: "{{ .Values.packageId }}-{{ .Values.Hierarchy.Name }}"
  sessionAffinity: None
  type: ClusterIP
