apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: "{{ .Values.packageId }}-{{ .Values.MedBridge.Name  }}"
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: "{{ .Values.packageId }}-{{ .Values.MedBridge.Name  }}"
    sessionAffinity: None
    type: ClusterIP