{{ if eq .Values.environment "production" }}

apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: "prod-medflix-db"
    labels:
      release: {{ .Release.Name }}
  spec:
    type: ExternalName
    externalName: {{ .Values.masterHost }}
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    sessionAffinity: None
- apiVersion: v1
  kind: Secret
  metadata:
    name: "prod-medflix-db"
  type: Opaque
  data:
    host: {{ .Values.masterHost | b64enc | quote }}
    name: {{ .Values.secret.name | b64enc | quote }}
    user: {{ .Values.secret.user | b64enc | quote }}
    password:  {{ .Values.secret.password | b64enc | quote }}


{{ end }}