# Default values for medbridge-ed-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  baseName: medflix-db
  # if this is set to ExternalName, no pods or persistent volumes will be intalled
  type: ClusterIP
  externalName: medflix-staging.c3qycbyc0w1w.us-west-1.rds.amazonaws.com
  externalPort: 3306
  internalPort: 3306

secret:
  name: course_recommendations
  user: medbridgeroot
  password: test123123

data:
  name: medflix-db-data

deployment:
  name: medflix-db
  image: mysql
  imageTag: 5.6