ReleasePath: /path/to/boatswain-values/deployment
Builds:
- Name: medbridge
  Path: deployment/build.sh
  RootPath: /Users/<name>/Programming/Php/Medbridge
- Name: medflix
  Path: deployment/build.sh
  RootPath: /Users/<name>/Programming/Php/Medflix/
- Name: ace
  Path: deployment/build.sh
  RootPath: /Users/<name>/Programming/Php/Ace
