apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.packageId }}-{{ .Values.App.Name }}
spec:
  type: {{ .Values.Service.Type }}
  ports:
  - port: {{ .Values.Service.ExternalPort }}
    targetPort: {{ .Values.Service.InternalPort }}
    protocol: TCP
    name: {{ .Values.Service.Name }}
  selector:
    app: {{ .Values.App.Name }}
