# Default values for medbridge-ed-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

masterHost: medbridge.us-west-1.rds.amazonaws.com

secret:
  name: medbridge_education
  user: username
  password: abc123