# Default values for ace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
configmap:
  name: ace-nginx-configmap
deployment:
  name: ace
  mountPath: /var/www
  hostPath: /Users/eric/Programing/php/ace-tracker
nginx:
  image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/ace-nginx
  imageTag: "11141da"
  pullPolicy: IfNotPresent
  internalPort: 80
phpfpm:
  image: 191682557156.dkr.ecr.us-east-1.amazonaws.com/medbridge/ace-phpfpm
  imageTag: "11141da"
  pullPolicy: IfNotPresent
  internalPort: 9000
service:
  name: ace-svc
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 1
    memory: 128Mi
  requests:
    cpu: 500m
    memory: 128Mi
databaseReference:
  medbridgeEd: medbridge-db
