apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: "{{ or .Values.packageId .Release.Name }}-{{ .Values.Persistence.Name }}"
    labels:
      app: medflix-pv
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      component: "{{ .Values.Component }}"
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
  spec:
    accessModes:
    -  "{{ .Values.Persistence.AccessMode }}"
    {{ if eq "staging" .Values.environment }}
    awsElasticBlockStore:
      fsType: ext4
      volumeID:  "{{ .Values.data.awsEbsVolumeId }}"
    {{ end }}
    {{ if eq "development" .Values.environment }}
    hostPath:
      path:  "{{ .Values.Persistence.Path }}"
    {{ end }}
    capacity:
      storage: "{{ .Values.Persistence.Size }}"
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "{{ or .Values.packageId .Release.Name }}-{{ .Values.data.claimName }}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: "{{ or .Values.packageId .Release.Name }}-{{ .Values.Persistence.Name }}"